Packaging
oshamashama/g-checker-for-itf pull request #2
Opened 2022-02-01 16:25 UTC by eggplants

主にPythonの部分に関する改善です。

- `pip install .` または `pip install -e .`で`gchk`コマンドを利用できるようにしました。
- `mypy --strict`時のエラーを無くしました。
- `black`と`isort`で整形しました。

```shellsession
$ gchk -h
usage: gchk [-h] [-i INPUT] [-r REQUIREMENTS] [-g] [-d] [-n] [-s] [-e] [-V]

This program is check that your credit can meet the graduation requirements.

optional arguments:
  -h, --help                  show this help message and exit
  -i INPUT, --input INPUT     target file from twins (UTF-8, CSV) (default: sample.csv)
  -r REQUIREMENTS, --requirements REQUIREMENTS
                              requirements file (default: coins20.json)
  -g, --gpa                   print GPA (default: False)
  -d, --drop                  print drop credit (default: True)
  -n, --name                  print name and id (default: False)
  -s, --save                  save as JSON (default: False)
  -e, --expect                count 履修中 (default: False)
  -V, --version               show program's version number and exit
```

2022-02-01 16:42 UTC, eggplants commented
![image](https://user-images.githubusercontent.com/42153744/152011331-48be850a-31df-4dc3-91a7-a104d1529396.png)

2022-02-01 18:42 UTC, eggplants commented
https://github.com/eggplants/g-checker-for-itf/blob/3ddaaf74fcd78a13a2d9229e17da151e20b4169f/g_checker_for_itf/Dir.py#L12-L13

ここだけmypyを黙らせていますが、これは再帰型が実装されていないためです。
https://github.com/python/mypy/issues/7069

2022-02-02 12:05 UTC, oshamashama requested changes
パッケージ化、かなりのリファクタリングありがとうございます。
```py
if type(hoge) is not fuga:
	continue
```
の `hoge` が `fuga` のサブクラスなので、全てここの `if` で終わっていて、 `gchk` などが死んでいたので
```py
if isinstance(hoge, fuga):
	continue
```
とするとよさそうです。

2022-02-02 12:05 UTC, oshamashama commented on g_checker_for_itf/main.py
> +    grade_points = {"A+": 4.3, "A": 4, "B": 3, "C": 2, "D": 1}
```suggestion
    grade_points = {"A+": 4.3, "A": 4, "B": 3, "C": 2, "D": 0}
```
D についてのグレードは 0 のようです。
https://www.tsukuba.ac.jp/education/ug-courses-gpa/

2022-02-02 12:05 UTC, oshamashama commented on g_checker_for_itf/Dir.py
> +                if type(item) is not Dir:
```suggestion
                if not isinstance(item, Dir):
```

2022-02-02 12:05 UTC, oshamashama commented on g_checker_for_itf/Dir.py
> +                if type(item) is not RecognizedFilter:
```suggestion
                if not isinstance(item, RecognizedFilter):
```

2022-02-02 12:05 UTC, oshamashama commented on g_checker_for_itf/Dir.py
> +            if type(item) is not Dir:
```suggestion
            if not isinstance(item, Dir):
```

2022-02-02 12:05 UTC, oshamashama commented on g_checker_for_itf/main.py
> +        if type(v1) is not Dir:
```suggestion
        if not isinstance(v1, Dir):
```

2022-02-02 12:05 UTC, oshamashama commented on g_checker_for_itf/main.py
> +            if type(v2) is not Dir:
```suggestion
            if not isinstance(v2, Dir):
```

2022-02-02 12:05 UTC, oshamashama commented on g_checker_for_itf/main.py
> +                if type(v3) is not Dir:
```suggestion
                if not isinstance(v3, Dir):
```

2022-02-02 12:05 UTC, oshamashama commented on g_checker_for_itf/main.py
> +                    if type(v4) is not Dir:
```suggestion
                    if not isinstance(v4, Dir):
```

2022-02-02 12:05 UTC, oshamashama commented on g_checker_for_itf/main.py
> +                        if type(v5) is not Dir:
```suggestion
                        if not isinstance(v5, Dir):
```

2022-02-02 12:21 UTC, eggplants commented on g_checker_for_itf/main.py
> +    grade_points = {"A+": 4.3, "A": 4, "B": 3, "C": 2, "D": 1}
https://github.com/oshamashama/g-checker-for-itf/blob/b6ac72838e50763dc2800eddf366f0c725dd6115/main.py#L243-L258

ここでは

2022-02-02 14:16 UTC, oshamashama approved these changes
よさそうです！色々ありがとうございます。

2022-02-02 14:16 UTC, merged